import asyncio
import sys
sys.path.append('c:/Users/minec/Documents/GitHub/The-Goats-Dj/discord-bot')
from dotenv import load_dotenv
load_dotenv('c:/Users/minec/Documents/GitHub/The-Goats-Dj/.env')

from src.core.database import init_db

async def migrate():
    await init_db()
    import src.core.database
    pool = src.core.database.db_pool
    
    async with pool.acquire() as conn:
        print("Starting FAST migration transaction...")
        async with conn.transaction():
            print("1. Creating tracks table...")
            await conn.execute('''
                CREATE TABLE IF NOT EXISTS tracks (
                    id SERIAL PRIMARY KEY,
                    artist_name VARCHAR(255) NOT NULL,
                    track_name VARCHAR(255) NOT NULL,
                    album_name VARCHAR(255) NOT NULL DEFAULT '',
                    UNIQUE(artist_name, track_name, album_name)
                );
            ''')
            
            print("2. Populating tracks table...")
            await conn.execute('''
                INSERT INTO tracks (artist_name, track_name, album_name)
                SELECT DISTINCT artist_name, track_name, COALESCE(album_name, '')
                FROM listens
                ON CONFLICT DO NOTHING;
            ''')
            
            print("3. Creating temporary new_listens table with fast Hash Join...")
            await conn.execute('''
                CREATE TABLE new_listens AS 
                SELECT l.id, l.user_id, l.played_at, l.spotify_uri, l.ms_played, t.id as track_id
                FROM listens l
                JOIN tracks t 
                  ON l.artist_name = t.artist_name 
                 AND l.track_name = t.track_name 
                 AND COALESCE(l.album_name, '') = t.album_name;
            ''')
            
            print("4. Swapping tables...")
            await conn.execute('DROP TABLE listens;')
            await conn.execute('ALTER TABLE new_listens RENAME TO listens;')
            
            print("5. Restoring primary key and sequences...")
            # Ensure the sequence is still linked correctly
            await conn.execute('''
                ALTER TABLE listens ADD PRIMARY KEY (id);
                ALTER TABLE listens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT setval(pg_get_serial_sequence('listens', 'id'), coalesce(max(id),0) + 1, false) FROM listens;
            ''')
            
            print("6. Creating indexes...")
            await conn.execute('CREATE INDEX IF NOT EXISTS idx_listens_track_id ON listens(track_id);')
            await conn.execute('CREATE INDEX IF NOT EXISTS idx_listens_user_id ON listens(user_id);')

        print("Migration complete! Transaction committed.")

asyncio.run(migrate())
